CamPhoneShop/WebMobileMVC/Models/KhuyenMai.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebMobileMVC.Models
{
    public class KhuyenMai
    {
        public int ID { get; set; }

        public string Ten { get; set; }

        public int IDNguoiTao { get; set; }

        public double PhamTramKM { get; set; }

        public DateTime NgayBatDau { get; set; }

        public DateTime NgayKetThuc { get; set; }

        public bool TinhTrang { get; set; }

        public string LoaiKhuyenMai { get; set; }

        public ICollection<ChiTietKhuyenMai> ChiTietKM { get; set; }
    }
}

CamPhoneShop/WebMobileMVC/Controllers/KhuyenMaiController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using WebMobileMVC.Models;

namespace WebMobileMVC.Controllers
{
    public class KhuyenMaiController : Controller
    {
        // GET: KhuyenMai
        public ActionResult Index()
        {
            DanhSachKhuyenMai listKM = new DanhSachKhuyenMai();
            using (WebClient webClient = new System.Net.WebClient())
            {
                var json = webClient.DownloadString("http://localhost:57233/api/khuyenmai/ok?idnguoitao=1");
                string valueOriginal = Convert.ToString(json);
                listKM = JsonConvert.DeserializeObject<DanhSachKhuyenMai>(valueOriginal);
            }
            
            return View(listKM);
        }

        // GET: KhuyenMai/Details/5
        public ActionResult Detail()
        {
            DanhSachKhuyenMai listKM = new DanhSachKhuyenMai();
            using (WebClient webClient = new System.Net.WebClient())
            {
                var json = webClient.DownloadString("http://localhost:57233/api/khuyenmai/ok?idnguoitao=1");
                string valueOriginal = Convert.ToString(json);
                listKM = JsonConvert.DeserializeObject<DanhSachKhuyenMai>(valueOriginal);
            }
            //ViewBag.chitiet = listKM.content[0].ChiTietKM;
            return View(listKM);
        }

        // GET: KhuyenMai/Create
        public ActionResult Create()
        {
            return View();
        }

        public void createKhuyenMai()
        {
            Redirect("/khuyenmai/Index");
        }

        // POST: KhuyenMai/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: KhuyenMai/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: KhuyenMai/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: KhuyenMai/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: KhuyenMai/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

CamPhoneShop/WebMobileMVC/Views/KhuyenMai/Create.cshtml
@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_LayoutSellers.cshtml";
}

<div class="content">
    <div class="animated fadeIn">
        <div class="row">
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-header">
                        <strong class="card-title" style="font-size: 25px">TẠO CHƯƠNG TRÌNH KHUYẾN MÃI MỚI</strong>
                    </div>
                    <div class="card-body">
                        <strong class="card-title" style="font-size: 18px">Thông Tin Khuyến Mãi</strong>
                        <br>
                        <br>
                        <form action="/khuyemai/createKhuyenMai" method="post" enctype="multipart/form-data" class="form-horizontal">
                            <div class="row form-group">
                                <div class="col col-md-3">
                                    <label for="text-input" class=" form-control-label">
                                        Tên
                                        Chương Trình Khuyến Mãi
                                    </label>
                                </div>
                                <div class="col col-md-7">
                                    <input type="text" id="txt_ctkm" name="txt_ctkm"
                                           placeholder="" class="form-control">
                                </div>
                            </div>
                            <div class="row form-group">
                                <div class="col col-md-3">
                                    <label for="text-input" class=" form-control-label">
                                        Thời gian khuyến mãi
                                    </label>
                                </div>

                                <div class="col col-md-7">
                                    <input type="text" class="form-control" name="datetimes" onchange="pickdate(this)" />
                                </div>
                            </div>
                            <div class="row form-group">
                                <div class="col col-md-3">
                                    <label for="text-input" class=" form-control-label">
                                        Phần trăm khuyến mãi
                                    </label>
                                </div>
                                <div class="col col-md-7">
                                    <input type="text" id="txt_phantram" name="txt_phantram"
                                           placeholder="" class="form-control">
                                </div>
                            </div>
                            <div class="row form-group">
                                <div class="col col-md-3">
                                    <label for="text-input" class=" form-control-label">
                                    </label>
                                </div>
                                <div class="col col-md-7">
                                    <button class="btn btn-primary btn-primary-custom pull-right">Lưu và tiếp tục</button>
                                </div>
                            </div>

                        </form>
                    </div>

                </div>
            </div><!-- /# column -->
        </div>
    </div>

CamPhoneShop/WebMobileMVC/Views/KhuyenMai/Index.cshtml
@{
    ViewData["Title"] = "View";
    Layout = "~/Views/Shared/_LayoutSellers.cshtml";
}

<style>

    .dataTables_wrapper.container-fluid.dt-bootstrap4.no-footer {
        padding: 0;
    }

    .btn-outline-custom {
        border: #ff5722;
        background: #ff5722;
    }

    .form-control:focus {
        border: 1px solid #ff5722;
        box-shadow: none;
    }

    .btn-outline-custom:hover {
        border: #ff5722;
        background: #ff5722;
    }

    #bootstrap-data-table_filter {
        display: none;
    }

    #bootstrap-data-table-1_filter {
        display: none
    }

    .actions-bar {
        display: flex;
        justify-content: space-between;
    }

    .bage-cus-available {
        background: #ff5722 !important;
        width: 100%;
    }

    .bage-cus-lock {
        background: #721c24 !important;
        width: 100%;
    }

    .bage-cus-out-of {
        background: #856404 !important;
        width: 100%;
    }

    i.fa {
        color: #ffffff;
    }

    .nav-link.nav-link-custom.active {
        background: #ff5722 !important;
        border: 0;
    }
</style>




<div class="content">
    <div class="animated fadeIn">
        <div class="row">
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-header">
                        <strong class="card-title" style="font-size: 25px">CHƯƠNG TRÌNH KHUYẾN MÃI</strong>
                    </div>
                    <div class="card-body">
                        <div class="row">
                            <div class="col-lg-12">
                                <a href="@Url.Action("Create", "KhuyenMai")" class="btn btn-success btn-primary-custom pull-right">
                                    <i class="fa fa-plus"></i> Tạo Chương Trình Khuyến Mãi mới
                                </a>
                            </div>
                        </div>
                        <br>

                        <div class="container">
                            <ul class="nav nav-pills">
                                <li class="nav-item">
                                    <a href="#1a" class="nav-link nav-link-custom active" data-toggle="tab">
                                        Khuyến mãi của Shop
                                    </a>
                                </li>

                                <li class="nav-item nav-item-custom">
                                    <a href="#2a" class="nav-link nav-link-custom" data-toggle="tab">
                                        Khuyến mãi của CAM PHONE SHOP
                                    </a>
                                </li>
                            </ul>

                            <div class="tab-content clearfix" style="margin-top: 15px;">
                                <div class="tab-pane active" id="1a">

                                    <div class="row" style="margin-bottom: 15px;">
                                        <div class="col-lg-12 actions-bar">
                                            <form class="form-inline my-2 my-lg-0">
                                                <input class="form-control mr-sm-2" type="search" placeholder="Nhập thông tin cần tìm ..."
                                                       aria-label="Search">

                                                <button class="btn btn-outline-primary btn-outline-custom my-2 my-sm-0"
                                                        type="submit">
                                                    <i class="fa fa-search"></i>
                                                </button>
                                            </form>
                                            <a href="createproduct.html" class="btn btn-success btn-primary-custom pull-right">
                                                <i class="fa fa-plus"></i></i> Thêm sản phẩm
                                            </a>
                                        </div>
                                    </div>

                                    <table id="bootstrap-data-table" class="table table-striped table-bordered">
                                        <thead>
                                            <tr>
                                                <th>Tên Chương Trình</th>
                                                <th>% Khuyến mãi</th>
                                                <th>Từ ngày</th>
                                                <th>Đến ngày</th>
                                                <th>Tình trạng</th>
                                                <th>Thao tác</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @foreach (KhuyenMai i in Model.content)
                                            {
                                                <tr>
                                                    <td>@i.Ten.Substring(0, 18) ...</td>
                                                    <td>@i.PhamTramKM</td>
                                                    <td>@i.NgayBatDau.ToShortDateString()</td>
                                                    <td>@i.NgayKetThuc.ToShortDateString()</td>
                                                    <td>
                                                        <span class="badge badge-danger bage-cus-out-of">
                                                            @i.TinhTrang
                                                        </span>
                                                    </td>
                                                    <td>
                                                        <a href="./promotionDetail.html" class="btn btn-sm btn-warning btn-primary-custom ">
                                                            <i class="fa fa-align-justify"></i>
                                                        </a>
                                                        <button class="btn btn-sm btn-warning btn-primary-custom">
                                                            <i class="fa fa-edit"></i>
                                                        </button>
                                                        <button class="btn btn-sm btn-warning btn-primary-custom">
                                                            <i class="fa fa-trash-o"></i>
                                                        </button>
                                                    </td>
                                                </tr>
                                            }
                                        </tbody>
                                    </table>
                                </div>

                                <div class="tab-pane" id="2a">

                                    <div class="row" style="margin-bottom: 15px;">
                                        <div class="col-lg-12 actions-bar">
                                            <form class="form-inline my-2 my-lg-0">
                                                <input class="form-control mr-sm-2" type="search" placeholder="Nhập thông tin cần tìm ..."
                                                       aria-label="Search">

                                                <button class="btn btn-outline-primary btn-outline-custom my-2 my-sm-0"
                                                        type="submit">
                                                    <i class="fa fa-search"></i>
                                                </button>
                                            </form>
                                            <a href="createproduct.html" class="btn btn-success btn-primary-custom pull-right">
                                                <i class="fa fa-plus"></i></i> Thêm sản phẩm
                                            </a>
                                        </div>
                                    </div>

                                    <table id="bootstrap-data-table-1" class="table table-striped table-bordered">
                                        <thead>
                                            <tr>
                                                <th>Tên Chương Trình</th>
                                                <th>% Khuyến mãi</th>
                                                <th>Từ ngày</th>
                                                <th>Đến ngày</th>
                                                <th>Tình trạng</th>
                                                <th>Thao tác</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <tr>
                                                <td>LỄ GIÁO VIÊN CÙNG CAM</td>
                                                <td>10</td>
                                                <td>23:00 09/11/2018</td>
                                                <td>00:00 10/11/2018</td>
                                                <td>
                                                    <span class="badge badge-danger bage-cus-out-of">
                                                        Đã kết
                                                        thúc
                                                    </span>
                                                </td>
                                                <td>
                                                    <a href="./promotionDetail.html" class="btn btn-sm btn-warning btn-primary-custom ">
                                                        <i class="fa fa-align-justify"></i>
                                                    </a>
                                                    <button class="btn btn-sm btn-warning btn-primary-custom">
                                                        <i class="fa fa-edit"></i>
                                                    </button>
                                                    <button class="btn btn-sm btn-warning btn-primary-custom">
                                                        <i class="fa fa-trash-o"></i>
                                                    </button>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>NOEL CÙNG CAM PHONE SHOP</td>
                                                <td>20</td>
                                                <td>23:00 09/11/2018</td>
                                                <td>00:00 10/11/2018</td>
                                                <td>
                                                    <span class="badge bage-cus-available badge-warning">
                                                        Đang
                                                        diễn ra
                                                    </span>
                                                    <!-- <span class="badge badge-danger bage-cus-out-of">Hết hàng</span>
                                                                            <span class="badge badge-danger bage-cus-lock">Đang bị khóa</span> -->
                                                <td>
                                                    <a href="./promotionDetail.html" class="btn btn-sm btn-warning btn-primary-custom ">
                                                        <i class="fa fa-align-justify"></i>
                                                    </a>
                                                    <button class="btn btn-sm btn-warning btn-primary-custom">
                                                        <i class="fa fa-edit"></i>
                                                    </button>
                                                    <button class="btn btn-sm btn-warning btn-primary-custom">
                                                        <i class="fa fa-trash-o"></i>
                                                    </button>
                                                </td>
                                            </tr>

                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>



</div>