CamPhoneShop/WebMobileMVC/Controllers/OrderSellerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using System.Net;
using Newtonsoft.Json;
using WebMobileMVC.Models;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace WebMobileMVC.Controllers
{
    public class OrderSellerController : Controller
    {
        // GET: /<controller>/
        public IActionResult Detail(int? id)
        {
            DSHoadon listHD = new DSHoadon();
            using (WebClient webClient = new System.Net.WebClient())
            {
                var json = webClient.DownloadString("http://localhost:57233/api/hoadon/getall?id=" + id);
                string valueOriginal = Convert.ToString(json);
                listHD = JsonConvert.DeserializeObject<DSHoadon>(valueOriginal);
            }
            return View(listHD);
        }
        public IActionResult Index(int? id)
        {
            DSHoadon listHD = new DSHoadon();
            using (WebClient webClient = new System.Net.WebClient())
            {
                var json = webClient.DownloadString("http://localhost:57233/api/hoadon/getall");
                string valueOriginal = Convert.ToString(json);
                listHD = JsonConvert.DeserializeObject<DSHoadon>(valueOriginal);
            }
            return View(listHD);
        }
    }
}

CamPhoneShop/WebMobileMVC/Views/OrderSeller/Detail.cshtml
@{
    Layout = "_LayoutSellers";
}
<style>
    .media-obj2 {
        justify-content: space-between;
    }
</style>
<div class="content">
    <div class="animated fadeIn">
        <div class="row" style="margin-bottom: -15px;">
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-body">
                        <strong class="card-title" style="font-size: 23px">CHI TIẾT ĐƠN HÀNG</strong>
                    </div>
                </div>
            </div><!-- /# column -->
        </div>
        @foreach (HoaDon x in Model.content)
        {
            <div class="row" style="margin-bottom: -15px;">
                <div class="col-lg-12">
                    <div class="card">
                        <div class="card-body">
                            <div class="media-obj2">
                                <div class="left">
                                    <div class="media media-custom">
                                        <i class="mr-3 fa fa-clipboard" style="font-size: larger; color: #ff5722;"></i>
                                        <div class="media-body">
                                            <div class="left">
                                                <h5 style="margin-bottom: 10px">
                                                    <strong class="card-title" style="font-size: 15px; color: #ff5722;">
                                                        @x.TinhTrangTT
                                                    </strong>
                                                </h5>
                                                <p style="font-size: 14px">
                                                    Đã giao hàng vào ngày @x.Ngay
                                                </p>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="right">
                                    <button type="button" class="btn btn-outline-warning btn-sm">Phê duyệt</button>
                                    <button type="button" class="btn btn-outline-warning btn-sm">Từ chối</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div><!-- /# column -->
            </div>
            <div class="row" style="margin-bottom: -15px;">
                <div class="col-lg-12">
                    <div class="card">
                        <div class="card-body">
                            <div class="media-obj2">
                                <div class="left">
                                    <div class="media">
                                        <i class="mr-3 fa fa-qrcode" style="font-size: larger; color: #ff5722;"></i>
                                        <div class="media-body">
                                            <h5 style="margin-bottom: 10px">
                                                <strong class="card-title" style="font-size: 15px;">
                                                    ID
                                                    Đơn hàng
                                                </strong>
                                            </h5>
                                            <p style="font-size: 14px">
                                                @x.ID
                                            </p>
                                        </div>
                                    </div>

                                    <div class="media">
                                        <i class="mr-3 fa fa-map-marker" style="font-size: larger; color: #ff5722;"></i>
                                        <div class="media-body">
                                            <h5 style="margin-bottom: 10px">
                                                <strong class="card-title" style="font-size: 15px;">
                                                    Địa
                                                    chỉ nhận hàng
                                                </strong>
                                            </h5>
                                            <p style="font-size: 14px">
                                                <div class="diachi" style="margin-top: -6px;">Long, 84939847299</div>
                                                <div class="diachi">
                                                    @x.DiaChiKH
                                                </div>
                                            </p>
                                        </div>
                                    </div>

                                    <div class="media">
                                        <i class="mr-3 fa fa-truck" style="font-size: larger; color: #ff5722;"></i>
                                        <div class="media-body">
                                            <h5 style="margin-bottom: 10px"><strong class="card-title" style="font-size: 15px;">Phương thức thanh toán</strong></h5>
                                            <p style="font-size: 14px">
                                                @x.PhuongThucTT
                                            </p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div><!-- /# column -->
            </div>
        }
        <div class="row" style="margin-bottom: -15px;">
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-body">
                        <div class="media">
                            <i class="mr-3 fa fa-dollar" style="font-size: larger; color: #ff5722;"></i>
                            <div class="media-body">
                                <h5 style="margin-bottom: 10px">
                                    <strong class="card-title" style="font-size: 15px;">
                                        Thông
                                        tin thanh toán
                                    </strong>
                                </h5>
                                <div class="table-stats order-table ov-h">
                                    <table class="table">
                                        <thead>
                                            <tr>
                                                <th class="avatar">Sản phẩm</th>
                                                <th>Đơn giá</th>
                                                <th>Số lượng </th>
                                                <th>Thành tiền</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @foreach (ChiTietHD i in Model.content[0].ChiTietHD)
                                            {
                                                <tr>
                                                    <td class="serial">@i.IDPhanLoaiSP</td>
                                                    <td> <span class="name">@i.Gia</span> </td>
                                                    <td> <span class="product">@i.Soluong</span> </td>
                                                    <td><span class="">@(i.Soluong*i.Gia)</span></td>
                                                </tr>
                                            }
                                        </tbody>
                                    </table>
                                </div> <!-- /.table-stats -->
                                <div class="row">
                                    <div class="col-lg-9">
                                        <div class="media">
                                            <div class="media-body" style="text-align: right;">
                                                <p class="ct">
                                                    Tổng tiền sản phẩm
                                                </p>
                                                <p class="ct">
                                                    Phí vận chuyển
                                                </p>
                                                <p class="ct">
                                                    Doanh thu
                                                </p>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-lg-3" style="text-align:right;">
                                        <div class="media">
                                            <div class="media-body" style="text-align: right; border-left: 1px solid lightgrey;">
                                                @foreach (HoaDon x in Model.content)
                                                {   
                                                    <p class="ctp">
                                                        @x.TongTien
                                                    </p>
                                                    <p class="ctp">
                                                        đ30.000
                                                    </p>
                                                    <p class="ctp">
                                                        <strong style="font-size: 22px; color: #ff5722">đ @(x.TongTien+30000)</strong>
                                                    </p>
                                                }
                                                
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div><!-- /# column -->
        </div>
    </div>
    <!-- /.content -->
</div>

CamPhoneShop/WebMobileMVC/Views/OrderSeller/Index.cshtml
@{
    Layout = "_LayoutSellers";
}
<div class="content">
    <div class="animated fadeIn">
        <div class="row">
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-header">
                        <strong class="card-title" style="font-size: 23px">QUẢN LÝ ĐƠN BÁN</strong>
                    </div>
                    <div class="card-body">
                        <div class="row">
                            <div class="col-lg-12">
                                <form class="form-inline my-2 my-lg-0">
                                    <input class="form-control mr-sm-2" type="search" placeholder="Nhập thông tin tìm kiếm..."
                                           aria-label="Search">
                                    <button class="btn btn-search my-2 my-sm-0" type="submit">Tìm kiếm</button>
                                </form>
                                <br>
                                <table id="bootstrap-data-table" class="table table-striped table-bordered">
                                    <thead>
                                        <tr>
                                            <th>Mã đơn hàng</th>
                                            <th>Ngày đặt hàng</th>
                                            <th>Tên khách hàng</th>
                                            <th>Số điện thoại</th>
                                            <th>Phương thức thanh toán</th>
                                            <th>Tổng tiền</th>
                                            <th>Tình trạng</th>
                                            <th>Thao tác</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach (HoaDon x in Model.content)
                                        {
                                            <tr>
                                                <td>@x.ID</td>
                                                <td>@x.Ngay</td>
                                                <td>@x.TenKH</td>
                                                <td>@x.SDT</td>
                                                <td>@x.PhuongThucTT</td>
                                                <td>@x.TongTien</td>
                                                @if (@x.TrangThai == true)
                                                {
                                                    <td><span class="badge badge-complete">Complete</span></td>
                                                }
                                                else
                                                {
                                                    <td><span class="badge badge-pending">Pending</span></td>
                                                }
                                                <td>
                                                    <a href="@Url.Action("Detail", "OrderSeller", new { id = x.ID })" class="btn btn-outline-warning btn-sm">Xem Chi tiết</a>
                                                </td>
                                            </tr>
                                        }
                                    </tbody>
                                </table>
                            </div>

                        </div> <!-- /.row -->
                    </div>
                </div>
            </div><!-- /# column -->
        </div>

        <!-- /.content -->
        <!-- /.site-footer -->
    </div>
    <!-- /#right-panel -->
</div>